baseURL = "https://fxshelll.github.io/"
languageCode = "pt-br"
title = "FXShell - DevOps & Sec"
theme = "after-dark"
enableRobotsTXT = true

# Realça de código
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  powered_by = false
  show_menu = true
  description = "Site pessoal com writeups de hacking, segurança e DevOps"
  author = "Felipe da Matta"

[[menu.main]]
  name = "home"
  weight = 1
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "anotações"
  weight = 2
  identifier = "post"
  url = "/posts/"

[[menu.main]]
  name = "HTB"
  weight = 3
  identifier = "htb"
  url = "/htb/"

[[menu.main]]
  name = "sobre"
  weight = 4
  identifier = "sobre"
  url = "/sobre/"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true