---
- name: Instalar HAProxy
  apt:
    name: haproxy
    state: present

- name: Permitir porta 80 no firewall
  ufw:
    rule: allow
    port: "80"
    proto: tcp

- name: Configurar HAProxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    validate: haproxy -c -f %s
  notify: Reiniciar HAProxy

- name: Garantir HAProxy rodando
  service:
    name: haproxy
    state: started
    enabled: yes
