Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  nodes = {
    "lb-01"  => "192.168.56.10",
    "web-01" => "192.168.56.11",
    "web-02" => "192.168.56.12",
    "db-01"  => "192.168.56.13"
  }

  nodes.each do |name, ip|
    config.vm.define name do |node|
      node.vm.hostname = name
      node.vm.network "private_network", ip: ip
      node.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        vb.cpus = 1
        vb.name = name
      end
    end
  end
end
