---
- name: Instalar Nginx
  apt:
    name: nginx
    state: present

- name: Permitir porta 80 apenas do load balancer
  ufw:
    rule: allow
    src: "192.168.56.10"
    port: "80"
    proto: tcp

- name: Criar página de health check
  copy:
    dest: /var/www/html/health
    content: "OK"
    owner: www-data
    group: www-data

- name: Criar página de identificação do servidor
  copy:
    dest: /var/www/html/index.html
    content: "<h1>Servidor: {{ inventory_hostname }}</h1>"
    owner: www-data
    group: www-data

- name: Garantir Nginx rodando
  service:
    name: nginx
    state: started
    enabled: yes
